// Assemble the static-deploy data tree the app fetches at runtime. Thin IO over
// the pure decisions in src/build/: glob the bundled presets' manifests, copy
// each preset's files, build the catalog; copy every font pack, splitting
// oversized faces into chunks (Cloudflare Pages caps files at 25 MiB); copy
// every locale pack + its index (a preset whose engineLocale has no engine
// builtin needs its pack text at setLocale); copy the wasm pkg.
// Coverage-excluded (scripts/ is not a coverage target) — the
// validation/tier/chunk logic it calls is unit-tested in src/build.
//
// This file is the DRIVER: the copy steps live beside it (`assemblePresets.ts`,
// `assembleAssets.ts`) over the shared paths in `assembleIo.ts`.
//
//   Usage (from gui/): pnpm --filter @shojiku/designer-app assemble
//   Output: gui/designer-app/dist/data/  (run after `vite build`)

import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
// `.ts` extensions: node runs this script under type stripping (no bundler), so
// the runtime import of the pure logic needs the explicit extension.
import { buildCatalog, buildFontIndex, buildLocaleIndex } from '../src/build/assemble.ts';
import { assembleFonts, assembleLocales, copyPkg } from './assembleAssets.ts';
import { copyFile, ensureDir, FONT_CATALOG, OUT, PKG } from './assembleIo.ts';
import { assemblePresets } from './assemblePresets.ts';

function main(): void {
  if (!existsSync(PKG)) {
    throw new Error(`${PKG} missing — run \`make engine:wasm\` before assembling the site`);
  }
  ensureDir(OUT);
  const presets = assemblePresets();
  const packs = assembleFonts();
  const localeFiles = assembleLocales();
  copyPkg();
  // The Google-Fonts catalog snapshot the font picker searches (checked in,
  // regenerated by scripts/gen-font-catalog.py).
  copyFile(FONT_CATALOG, join(OUT, 'font-catalog.json'));
  writeFileSync(join(OUT, 'catalog.json'), `${JSON.stringify(buildCatalog(presets), null, 2)}\n`);
  ensureDir(join(OUT, 'fonts'));
  writeFileSync(
    join(OUT, 'fonts', 'index.json'),
    `${JSON.stringify(buildFontIndex(packs), null, 2)}\n`,
  );
  writeFileSync(
    join(OUT, 'locale', 'index.json'),
    `${JSON.stringify(buildLocaleIndex(localeFiles), null, 2)}\n`,
  );
  process.stdout.write(
    `assembled ${presets.length} presets, ${packs.length} font packs, ` +
      `${localeFiles.length} locale packs → ${OUT}\n`,
  );
}

main();
