//! Builtin locale packs (CLDR-generated YAML, compiled in via
//! `include_str!`) and the per-key overlay merge over them.
//!
//! The YAML under `builtin/` is regenerated by
//! `scripts/gen-locale-builtins.py` (authoring-time; never runs in CI).
//! A `packs/locale/<id>.yml` file is an *overlay*: mappings merge per key
//! (recursively), scalars and sequences replace.

use super::{LangPack, LangPackError};
use serde_yaml::Value;

/// Locale ids compiled into this engine build (surfaced through
/// `shojiku capabilities` for GUI gating).
pub const BUILTIN_LOCALE_IDS: &[&str] = &["ja-JP", "en-US"];

const BUILTIN_YAML: [(&str, &str); 2] = [
    ("ja-JP", include_str!("builtin/ja-jp.yml")),
    ("en-US", include_str!("builtin/en-us.yml")),
];

/// The CLDR `currencyData` fractions table (code → decimal digits),
/// generated alongside the packs. Locale-independent supplemental data,
/// so it is compiled in ONCE here rather than copied per pack; it is why
/// an unlisted currency still gets the right precision (a 12.34
/// XYZ amount must not silently truncate to `XYZ 12`).
const FRACTIONS_YAML: &str = include_str!("builtin/currency-fractions.yml");

/// Decimal digits for an ISO currency code per CLDR (`DEFAULT` = 2).
/// Codes are matched case-sensitively (ISO codes are uppercase).
pub fn currency_fraction_digits(code: &str) -> u32 {
    static TABLE: std::sync::OnceLock<std::collections::BTreeMap<String, u32>> =
        std::sync::OnceLock::new();
    let table = TABLE.get_or_init(|| {
        // The file is generated + checked in; a parse failure is a build
        // defect caught by tests, so degrade to an empty table (every
        // code then gets the CLDR DEFAULT of 2) rather than panic.
        serde_yaml::from_str(FRACTIONS_YAML).unwrap_or_default()
    });
    table.get(code).copied().unwrap_or(2)
}

/// Resolves `id` against a builtin id list: case-insensitive exact match
/// first, then a unique bare-language prefix match (`ja` → `ja-JP`).
/// Ambiguous prefixes match nothing.
fn canonical_id(id: &str, ids: &[&'static str]) -> Option<&'static str> {
    if let Some(exact) = ids.iter().find(|c| c.eq_ignore_ascii_case(id)) {
        return Some(exact);
    }
    let mut hits = ids.iter().filter(|c| {
        c.len() > id.len()
            && c.as_bytes()[id.len()] == b'-'
            && c[..id.len()].eq_ignore_ascii_case(id)
    });
    match (hits.next(), hits.next()) {
        (Some(one), None) => Some(one),
        _ => None,
    }
}

/// Deep-merges `overlay` into `base`: mappings merge per key
/// (recursively); scalars, sequences, and nulls replace. Recursion depth
/// is bounded by the YAML parser's own nesting limit.
fn deep_merge(base: &mut Value, overlay: Value) {
    match (base, overlay) {
        (Value::Mapping(b), Value::Mapping(o)) => {
            for (key, value) in o {
                match b.get_mut(&key) {
                    Some(slot) => deep_merge(slot, value),
                    None => {
                        b.insert(key, value);
                    }
                }
            }
        }
        (slot, value) => *slot = value,
    }
}

impl LangPack {
    /// The builtin pack for `id` (see [`BUILTIN_LOCALE_IDS`]); matching is
    /// case-insensitive and a bare language tag selects its unique builtin
    /// (`ja` → `ja-JP`). When `overlay` YAML is given it is deep-merged
    /// per key over the builtin (overlay wins). `Ok(None)` when no
    /// builtin matches — the overlay is not parsed in that case.
    pub fn builtin(id: &str, overlay: Option<&str>) -> Result<Option<Self>, LangPackError> {
        // Match over BUILTIN_YAML itself so a stale BUILTIN_LOCALE_IDS
        // cannot create a panic path; a test pins the two lists equal.
        let Some(yaml) = builtin_yaml(id) else {
            return Ok(None);
        };
        let pack = match overlay {
            None => Self::from_yaml_str(yaml)?,
            Some(overlay) => {
                let mut base: Value = serde_yaml::from_str(yaml)?;
                deep_merge(&mut base, serde_yaml::from_str(overlay)?);
                serde_yaml::from_value(base)?
            }
        };
        Ok(Some(pack))
    }
}

fn builtin_yaml(id: &str) -> Option<&'static str> {
    let canonical = canonical_id(id, &BUILTIN_YAML.map(|(id, _)| id))?;
    BUILTIN_YAML
        .iter()
        .find(|(id, _)| *id == canonical)
        .map(|(_, yaml)| *yaml)
}

#[cfg(test)]
mod tests;
