#!/usr/bin/env python3
"""Generate the UAX#50 Vertical_Orientation table for engine/layout.

Reads VerticalOrientation.txt (Unicode 16.0.0, pinned) and emits
engine/layout/src/font/vertical/uax50.rs: the merged codepoint ranges
whose Vertical_Orientation is U, Tu, or Tr (everything drawn upright in
`text-orientation: mixed`; Tu/Tr transforms ride the font's GSUB `vert`
feature). The property default (@missing) is R, so the table lists the
upright ranges and the lookup answers "rotated" for everything else.

Usage:
  scripts/gen-uax50.py [path/to/VerticalOrientation.txt]

With no argument the data file is downloaded from unicode.org (the
pinned version below). Authoring-time tooling — never part of render.
"""

import sys
import urllib.request
from pathlib import Path

UNICODE_VERSION = "16.0.0"
URL = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/VerticalOrientation.txt"
OUT = Path(__file__).resolve().parent.parent / "engine/layout/src/font/vertical/uax50.rs"

HEADER = f"""//! UAX#50 Vertical_Orientation upright ranges — GENERATED by
//! `scripts/gen-uax50.py` from VerticalOrientation.txt (Unicode
//! {UNICODE_VERSION}); do not edit by hand. A codepoint listed here has
//! property U, Tu, or Tr (drawn upright in `text-orientation: mixed`;
//! the Tu/Tr typographic transform rides the font's GSUB `vert`
//! feature). Everything absent is R (rotated), the property default.

/// Merged, sorted inclusive ranges of upright codepoints.
"""

FOOTER = """
/// True when UAX#50 gives `c` Vertical_Orientation U, Tu, or Tr — the
/// full-property replacement for the closed v1 range set. Total over
/// `char` (absent codepoints are R, the property default).
pub(in crate::font) fn is_upright(c: char) -> bool {
    let cp = u32::from(c);
    UPRIGHT
        .binary_search_by(|&(lo, hi)| {
            if hi < cp {
                std::cmp::Ordering::Less
            } else if lo > cp {
                std::cmp::Ordering::Greater
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}
"""


def parse(lines):
    entries = []
    for line in lines:
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        rng, val = (f.strip() for f in line.split(";"))
        if val == "R":
            continue
        assert val in ("U", "Tu", "Tr"), val
        if ".." in rng:
            lo, hi = (int(p, 16) for p in rng.split(".."))
        else:
            lo = hi = int(rng, 16)
        entries.append((lo, hi))
    entries.sort()
    merged = []
    for lo, hi in entries:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], hi)
        else:
            merged.append([lo, hi])
    return merged


def main():
    if len(sys.argv) > 1:
        text = Path(sys.argv[1]).read_text()
    else:
        with urllib.request.urlopen(URL) as r:
            text = r.read().decode()
    merged = parse(text.splitlines())
    body = [f"const UPRIGHT: [(u32, u32); {len(merged)}] = ["]
    for lo, hi in merged:
        body.append(f"    (0x{lo:04X}, 0x{hi:04X}),")
    body.append("];")
    OUT.write_text(HEADER + "\n".join(body) + "\n" + FOOTER)
    print(f"wrote {OUT} ({len(merged)} ranges)")


if __name__ == "__main__":
    main()
