// The practice document at the start of every chapter, so a reader can jump to
// (or resume at) any chapter and find the page in the state its copy describes.
// Each one is the document the PREVIOUS chapter's steps produce.
//
// Every seed here has been rendered by the real engine against `PRACTICE_PARAMS`
// and is diagnostics-clean — the suite in this package pins that, because a
// tutorial that teaches from a warning-emitting page teaches the warning too.
//
// Data keys are ASCII: the engine interpolates `{key}` over `[A-Za-z0-9_.]`
// only, so a Japanese-named key works as a whole-item binding but would print
// literally inside a sentence. Every bundled ja example follows the same
// convention, and the course teaches it.

export const CHAPTER_SEEDS: Record<string, string> = {
  ch0: 'version: 0.1.0\nname: tutorial_practice\n\npage:\n  size: A4\n  margin: 25\n\ndefaults:\n  locale: ja-JP\n  currency: JPY\n  style:\n    fontFamily: biz-udp-gothic\n    fontSize: 10.5\n\nsections:\n  body:\n    type: flow\n    items: []\n',
  ch1: 'version: 0.1.0\nname: tutorial_practice\n\npage:\n  size: A4\n  margin: 24\n\ndefaults:\n  locale: ja-JP\n  currency: JPY\n  style:\n    fontFamily: biz-udp-gothic\n    fontSize: 10.5\n\nsections:\n  body:\n    type: flow\n    items: []\n',
  ch2: 'version: 0.1.0\nname: tutorial_practice\n\npage:\n  size: A4\n  margin: 24\n\ndefaults:\n  locale: ja-JP\n  currency: JPY\n  style:\n    fontFamily: biz-udp-gothic\n    fontSize: 10.5\n\nstyles:\n  タイトル:\n    fontSize: 21\n    fontWeight: bold\n    textAlign: center\n\nsections:\n  body:\n    type: flow\n    items:\n      - type: text\n        text: 御請求書\n        styleNames: [タイトル]\n',
  ch3: "version: 0.1.0\nname: tutorial_practice\n\npage:\n  size: A4\n  margin: 24\n\ndefaults:\n  locale: ja-JP\n  currency: JPY\n  style:\n    fontFamily: biz-udp-gothic\n    fontSize: 10.5\n\nstyles:\n  タイトル:\n    fontSize: 21\n    fontWeight: bold\n    textAlign: center\n\nsections:\n  body:\n    type: flow\n    items:\n      - type: text\n        text: 御請求書\n        styleNames: [タイトル]\n      - type: container\n        box: { direction: row, gap: 8 }\n        items:\n          - type: text\n            text: 株式会社サンプル商事 御中\n            box: { flexGrow: 1 }\n          - type: text\n            text: '請求日: '\n            box: { flexGrow: 2 }\n          - type: text\n            text: 'No. '\n            box: { flexGrow: 1 }\n",
  ch4: "version: 0.1.0\nname: tutorial_practice\n\npage:\n  size: A4\n  margin: 24\n\ndefaults:\n  locale: ja-JP\n  currency: JPY\n  style:\n    fontFamily: biz-udp-gothic\n    fontSize: 10.5\n\nstyles:\n  タイトル:\n    fontSize: 21\n    fontWeight: bold\n    textAlign: center\n\nsections:\n  body:\n    type: flow\n    items:\n      - type: text\n        text: 御請求書\n        styleNames: [タイトル]\n      - type: container\n        box: { direction: row, gap: 8 }\n        items:\n          - type: text\n            data: { key: customer }\n            box: { flexGrow: 1 }\n          - type: text\n            text: '請求日: {date}'\n            box: { flexGrow: 2 }\n          - type: text\n            text: 'No. INV-001'\n            box: { flexGrow: 1 }\n",
  ch5: "version: 0.1.0\nname: tutorial_practice\n\npage:\n  size: A4\n  margin: 24\n\ndefaults:\n  locale: ja-JP\n  currency: JPY\n  style:\n    fontFamily: biz-udp-gothic\n    fontSize: 10.5\n\nstyles:\n  タイトル:\n    fontSize: 21\n    fontWeight: bold\n    textAlign: center\n\nsections:\n  body:\n    type: flow\n    items:\n      - type: text\n        text: 御請求書\n        styleNames: [タイトル]\n      - type: container\n        box: { direction: row, gap: 8 }\n        items:\n          - type: text\n            data: { key: customer }\n            box: { flexGrow: 1 }\n          - type: text\n            text: '請求日: {date}'\n            box: { flexGrow: 2 }\n          - type: text\n            text: 'No. INV-001'\n            box: { flexGrow: 1 }\n      - type: table\n        data: { key: items }\n        header:\n          style: { backgroundColor: \"#ededed\", fontWeight: bold }\n        columns:\n          - label: 品名\n            data: { key: name }\n          - label: 数量\n            data: { key: qty }\n            width: 60\n            style: { textAlign: right }\n          - label: 単価\n            data: { key: price }\n            width: 80\n            style: { textAlign: right }\n          - label: 金額\n            data: { key: amount, format: symbol }\n            width: 90\n            style: { textAlign: right }\n",
  ch6: "version: 0.1.0\nname: tutorial_practice\n\npage:\n  size: A4\n  margin: 24\n\ndefaults:\n  locale: ja-JP\n  currency: JPY\n  style:\n    fontFamily: biz-udp-gothic\n    fontSize: 10.5\n\nstyles:\n  タイトル:\n    fontSize: 21\n    fontWeight: bold\n    textAlign: center\n\nsections:\n  body:\n    type: flow\n    items:\n      - type: text\n        text: 御請求書\n        styleNames: [タイトル]\n      - type: container\n        box: { direction: row, gap: 8 }\n        items:\n          - type: text\n            data: { key: customer }\n            box: { flexGrow: 1 }\n          - type: text\n            text: '請求日: {date}'\n            box: { flexGrow: 2 }\n          - type: text\n            text: 'No. INV-001'\n            box: { flexGrow: 1 }\n      - type: table\n        data: { key: items }\n        header:\n          style: { backgroundColor: \"#ededed\", fontWeight: bold }\n        columns:\n          - label: 品名\n            data: { key: name }\n          - label: 数量\n            data: { key: qty }\n            width: 60\n            style: { textAlign: right }\n          - label: 単価\n            data: { key: price }\n            width: 80\n            style: { textAlign: right }\n          - label: 金額\n            data: { key: amount, format: symbol }\n            width: 90\n            style: { textAlign: right }\n      - type: container\n        box: { direction: row, gap: 8 }\n        items:\n          - type: text\n            text: ''\n            box: { flexGrow: 3 }\n          - type: text\n            text: '合計 {total:symbol}'\n            box: { flexGrow: 1 }\n            style: { fontWeight: bold }\n",
  ch7: "version: 0.1.0\nname: tutorial_practice\n\npage:\n  size: A4\n  margin: 24\n\ndefaults:\n  locale: ja-JP\n  currency: JPY\n  style:\n    fontFamily: biz-udp-gothic\n    fontSize: 10.5\n\nstyles:\n  タイトル:\n    fontSize: 21\n    fontWeight: bold\n    textAlign: center\n\nsections:\n  body:\n    type: flow\n    items:\n      - type: text\n        text: 御請求書\n        styleNames: [タイトル]\n      - type: container\n        box: { direction: row, gap: 8 }\n        items:\n          - type: text\n            data: { key: customer }\n            box: { flexGrow: 1 }\n          - type: text\n            text: '請求日: {date}'\n            box: { flexGrow: 2 }\n          - type: text\n            text: 'No. INV-001'\n            box: { flexGrow: 1 }\n      - type: table\n        data: { key: items }\n        header:\n          style: { backgroundColor: \"#ededed\", fontWeight: bold }\n        columns:\n          - label: 品名\n            data: { key: name }\n          - label: 数量\n            data: { key: qty }\n            width: 60\n            style: { textAlign: right }\n          - label: 単価\n            data: { key: price }\n            width: 80\n            style: { textAlign: right }\n          - label: 金額\n            data: { key: amount, format: symbol }\n            width: 90\n            style: { textAlign: right }\n      - type: container\n        box: { direction: row, gap: 8 }\n        items:\n          - type: text\n            text: ''\n            box: { flexGrow: 3 }\n          - type: text\n            text: '合計 {total:symbol}'\n            box: { flexGrow: 1 }\n            style: { fontWeight: bold }\n  footer:\n    repeat: every_page\n    height: 40\n    items:\n      - type: text\n        text: 株式会社ショウジク\n        box: { x: 24, y: 762, w: 200, h: 16 }\n      - type: page_number\n        box: { x: 0, y: 778, w: \"100%\", h: 13 }\n        style: { fontSize: 8, textAlign: center }\n",
  ch8: 'version: 0.1.0\nname: tutorial_practice\n\npage:\n  size: A4\n  margin: 24\n\ndefaults:\n  locale: ja-JP\n  currency: JPY\n  style:\n    fontFamily: biz-udp-gothic\n    fontSize: 10.5\n\nstyles:\n  タイトル:\n    fontSize: 21\n    fontWeight: bold\n    textAlign: center\n\nsections:\n  body:\n    type: flow\n    items:\n      - type: text\n        text: 御請求書\n        styleNames: [タイトル]\n      - type: container\n        box: { direction: row, gap: 8 }\n        items:\n          - type: text\n            data: { key: customer }\n            box: { flexGrow: 1 }\n          - type: text\n            text: \'請求日: {date}\'\n            box: { flexGrow: 2 }\n          - type: text\n            text: \'No. INV-001\'\n            box: { flexGrow: 1 }\n      - type: table\n        data: { key: items }\n        header:\n          style: { backgroundColor: "#ededed", fontWeight: bold }\n        columns:\n          - label: 品名\n            data: { key: name }\n          - label: 数量\n            data: { key: qty }\n            width: 60\n            style: { textAlign: right }\n          - label: 単価\n            data: { key: price }\n            width: 80\n            style: { textAlign: right }\n          - label: 金額\n            data: { key: amount, format: symbol }\n            width: 90\n            style: { textAlign: right }\n      - type: container\n        box: { direction: row, gap: 8 }\n        items:\n          - type: text\n            text: \'\'\n            box: { flexGrow: 3 }\n          - type: text\n            text: \'合計 {total:symbol}\'\n            box: { flexGrow: 1 }\n            style: { fontWeight: bold }\n      - type: image\n        src: \'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60"><circle cx="30" cy="30" r="27" fill="none" stroke="#c0392b" stroke-width="3"/><circle cx="30" cy="30" r="19" fill="none" stroke="#c0392b" stroke-width="2"/><path d="M20 30h20M30 20v20" stroke="#c0392b" stroke-width="2"/></svg>\'\n        box: { x: 480, y: 40, w: 60, h: 60 }\n  footer:\n    repeat: every_page\n    height: 40\n    items:\n      - type: text\n        text: 株式会社ショウジク\n        box: { x: 24, y: 762, w: 200, h: 16 }\n      - type: page_number\n        box: { x: 0, y: 778, w: "100%", h: 13 }\n        style: { fontSize: 8, textAlign: center }\n',
};

/** Practice documents for the topic shorts that need structure the chapter
 * seeds don't provide. `footer` is a titled body plus a footer band carrying
 * only a page number, so the footer topic fills in the company-name text itself. Same
 * diagnostics-clean guarantee (and the same integration pin) as the chapter
 * seeds — the footer band mirrors the course's own (ch7), which is pinned. */
export const TOPIC_SEEDS: Record<string, string> = {
  footer:
    'version: 0.1.0\nname: tutorial_practice\n\npage:\n  size: A4\n  margin: 24\n\ndefaults:\n  locale: ja-JP\n  currency: JPY\n  style:\n    fontFamily: biz-udp-gothic\n    fontSize: 10.5\n\nsections:\n  body:\n    type: flow\n    items:\n      - type: text\n        text: 御請求書\n  footer:\n    repeat: every_page\n    height: 40\n    items:\n      - type: page_number\n        box: { x: 0, y: 778, w: "100%", h: 13 }\n        style: { fontSize: 8, textAlign: center }\n',
};

/** The sample data the practice document is bound to. Values are Japanese;
 * keys are ASCII (see above). */
export const PRACTICE_PARAMS =
  '{\n  "customer": "株式会社サンプル商事",\n  "date": "2026-07-01",\n  "total": 300000,\n  "items": [\n    {\n      "name": "デザイン制作費",\n      "qty": 1,\n      "price": 200000,\n      "amount": 200000\n    },\n    {\n      "name": "写真撮影費",\n      "qty": 2,\n      "price": 50000,\n      "amount": 100000\n    },\n    {\n      "name": "サーバー保守費",\n      "qty": 1,\n      "price": 30000,\n      "amount": 30000\n    }\n  ]\n}';
